server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://shopper-db.c4biysdam7a3.us-east-1.rds.amazonaws.com:3306/shopper-db
    username: tcsyellow
    password: tcsyellow
